# Generated by Django 5.2.4 on 2025-08-29 15:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_booking_options_alter_bus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='conductor',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.trip'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='conductor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='core.conductor'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conductor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('trip', 'seat_number'), name='unique_trip_seat'),
        ),
    ]
