# Generated by Django 5.2.4 on 2025-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_route_remove_conductor_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_time']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['departure_time']},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('passenger', 'trip')},
        ),
    ]
