# Generated by Django 5.2.4 on 2025-08-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_options_conductor_employee_id_ticket_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.trip'),
        ),
    ]
